services:
  contractlens-frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: contractlens-frontend
    env_file:
      - .env
    ports:
      - "3000:3000"

  contractlens-backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: contractlens-backend
    env_file:
      - .env
    ports:
      - "8000:8000"
